name: Deploy character sheets

on:
  push:
    branches:
      - deploy/char-sheet

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./char-sheet
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: node-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('./char-sheet/package.json') }}
      - name: Install node packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Sync to S3
        run: aws s3 sync ./build s3://caltrops-bucket --delete
      - name: Invalidate cloudfront cache
        run: export AWS_PAGER=""; aws cloudfront create-invalidation --distribution-id E1DB54COCE13CS --paths '/*';
        

