name: Deploy server lambda

on:
  push:
    branches:
      - deploy/server

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - run: zip -r ./function.zip ./src
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - run: aws lambda update-function-code --function-name caltrops-lambda --zip-file 'fileb://function.zip'
      
        

